export const combatItems = {
  health_potion: {
    id: 'health_potion',
    name: 'Health Potion',
    description: 'Recovers 20 HP when used in combat.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🧪',
    useInCombat: true
  },
  xp_potion: {
    id: 'xp_potion',
    name: 'XP Potion',
    description: 'Use in battle to gain 50 XP.',
    type: 'consumable',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🧪',
    useInCombat: true
  },
  faded_blade: {
    id: 'faded_blade',
    name: 'Faded Blade',
    description:
      'A worn weapon once carried by Vaelin. Use in battle to strike harder.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 1,
    icon: '🗡️',
    useInCombat: true
  },
  mana_gem: {
    id: 'mana_gem',
    name: 'Mana Gem',
    description: 'Refreshes all skill cooldowns once.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 99,
    icon: '🔮',
    useInCombat: true
  },
  arcane_spark: {
    id: 'arcane_spark',
    name: 'Arcane Spark',
    description: 'Unleashes a burst damaging all foes once per battle.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 3,
    icon: '✨',
    useInCombat: true
  },
  defense_potion_II: {
    id: 'defense_potion_II',
    name: 'Defense Potion II',
    description: 'Increases defense by 2 for this fight.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 10,
    icon: '🧴',
    useInCombat: true
  },
  defensive_potion_ii: {
    id: 'defensive_potion_ii',
    name: 'Defensive Potion II',
    description: 'Increases defense by 2 for this fight.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 10,
    icon: '🛡️',
    useInCombat: true
  },
  stamina_dust: {
    id: 'stamina_dust',
    name: 'Stamina Dust',
    description: 'Restores one skill cooldown instantly.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 10,
    icon: '💨',
    useInCombat: true
  },
  reflect_potion: {
    id: 'reflect_potion',
    name: 'Reflect Potion',
    description: 'Reflects the next damage back to the enemy.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🔄',
    useInCombat: true
  },
  mana_scroll: {
    id: 'mana_scroll',
    name: 'Mana Scroll',
    description: 'Completely restores skill cooldowns.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 3,
    icon: '📜',
    useInCombat: true
  },
  clarity_shard: {
    id: 'clarity_shard',
    name: 'Clarity Shard',
    description: 'Use in combat to clear debuffs and gain "Focus".',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 3,
    icon: '🔷',
    useInCombat: true
  },
  mana_ember: {
    id: 'mana_ember',
    name: 'Mana Ember',
    description: 'Restores skill energy when used in combat.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🔥',
    useInCombat: true
  },
  volcanic_slag: {
    id: 'volcanic_slag',
    name: 'Volcanic Slag',
    description: 'Powers up fiery abilities when used in combat.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🌋',
    useInCombat: true
  }
};
