// AUTO-GENERATED BY tools/build_npc_index.js
// DO NOT EDIT MANUALLY

import * as arbiter from './arbiter.js';
import * as arvalin from './arvalin.js';
import * as breathless_night from './breathless_night.js';
import * as caelen from './caelen.js';
import * as coren from './coren.js';
import * as corruption_shrine from './corruption_shrine.js';
import * as darius_the_conversationalist from './darius_the_conversationalist.js';
import * as dream_echo1 from './dream_echo1.js';
import * as dream_echo2 from './dream_echo2.js';
import * as echo from './echo.js';
import * as echo_memory from './echo_memory.js';
import * as echo_self_flame from './echo_self_flame.js';
import * as echo_self_peace from './echo_self_peace.js';
import * as echo_self_shadow from './echo_self_shadow.js';
import * as ember from './ember.js';
import * as eryndor from './eryndor.js';
import * as field_note_disintegration from './field_note_disintegration.js';
import * as first_memory from './first_memory.js';
import * as flamebound from './flamebound.js';
import * as forge_npc from './forge_npc.js';
import * as fork_guide from './fork_guide.js';
import * as frederica from './frederica.js';
import * as goblin_quest_giver from './goblin_quest_giver.js';
import * as grindle from './grindle.js';
import * as kaelor_the_weaver from './kaelor_the_weaver.js';
import * as korell from './korell.js';
import * as krealer from './krealer.js';
import * as krealer1 from './krealer1.js';
import * as krealer2 from './krealer2.js';
import * as krealer3 from './krealer3.js';
import * as krealer4 from './krealer4.js';
import * as krealer5 from './krealer5.js';
import * as krealer6 from './krealer6.js';
import * as krealer7 from './krealer7.js';
import * as krealer8 from './krealer8.js';
import * as leda from './leda.js';
import * as lioran from './lioran.js';
import * as lore_obelisk from './lore_obelisk.js';
import * as lore_statue from './lore_statue.js';
import * as map08_npc from './map08_npc.js';
import * as myralen from './myralen.js';
import * as npc_01 from './npc_01.js';
import * as npc_02 from './npc_02.js';
import * as npc_03 from './npc_03.js';
import * as npc_04 from './npc_04.js';
import * as relic_chamber from './relic_chamber.js';
import * as ruins_scholar from './ruins_scholar.js';
import * as second_voice from './second_voice.js';
import * as shade_sage from './shade_sage.js';
import * as silari_the_analyst from './silari_the_analyst.js';
import * as silent_monument from './silent_monument.js';
import * as snealer from './snealer.js';
import * as syranel from './syranel.js';
import * as thalos from './thalos.js';
import * as timara from './timara.js';
import * as vaelin from './vaelin.js';
import * as vaultkeeper from './vaultkeeper.js';
import * as veil from './veil.js';
import * as verrel_the_voice from './verrel_the_voice.js';
import * as watcher from './watcher.js';

export const npcModules = {
  arbiter,
  arvalin,
  breathless_night,
  caelen,
  coren,
  corruption_shrine,
  darius_the_conversationalist,
  dream_echo1,
  dream_echo2,
  echo,
  echo_memory,
  echo_self_flame,
  echo_self_peace,
  echo_self_shadow,
  ember,
  eryndor,
  field_note_disintegration,
  first_memory,
  flamebound,
  forge_npc,
  fork_guide,
  frederica,
  goblin_quest_giver,
  grindle,
  kaelor_the_weaver,
  korell,
  krealer,
  krealer1,
  krealer2,
  krealer3,
  krealer4,
  krealer5,
  krealer6,
  krealer7,
  krealer8,
  leda,
  lioran,
  lore_obelisk,
  lore_statue,
  map08_npc,
  myralen,
  npc_01,
  npc_02,
  npc_03,
  npc_04,
  relic_chamber,
  ruins_scholar,
  second_voice,
  shade_sage,
  silari_the_analyst,
  silent_monument,
  snealer,
  syranel,
  thalos,
  timara,
  vaelin,
  vaultkeeper,
  veil,
  verrel_the_voice,
  watcher
};
