export const itemData = {
  map02_key: {
    id: 'map02_key',
    name: 'Map02 Key',
    description: 'Required to unlock the path to the next map.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: false,
    stackLimit: 1,
    icon: '🗝️'
  },
  temple_key: {
    id: 'temple_key',
    name: 'Temple Key',
    description: 'Opens the sealed temple gate.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: false,
    stackLimit: 1,
    icon: '🗝️'
  },
  temple_chest_key: {
    id: 'temple_chest_key',
    name: 'Temple Chest Key',
    description: 'Opens special chests within the temple.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: true,
    stackLimit: 1,
    icon: '🗝️'
  },
  health_potion: {
    id: 'health_potion',
    name: 'Health Potion',
    description: 'Recovers 20 HP when used in combat.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🧪',
    useInCombat: true
  },
  xp_scroll: {
    id: 'xp_scroll',
    name: 'XP Scroll',
    description: 'Use to gain 25 experience.',
    type: 'consumable',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '📜',
    use() {
      import('./player.js').then((m) => m.gainXP(25));
    }
  },
  xp_potion: {
    id: 'xp_potion',
    name: 'XP Potion',
    description: 'Use in battle to gain 50 XP.',
    type: 'consumable',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🧪',
    useInCombat: true,
    use() {
      import('./player.js').then((m) => m.gainXP(50));
    }
  },
  xp_relic: {
    id: 'xp_relic',
    name: 'XP Relic',
    description: 'Grants 100 XP when used from your pack.',
    type: 'consumable',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 1,
    icon: '🔮',
    inventoryOnly: true,
    use() {
      import('./player.js').then((m) => m.gainXP(100));
    }
  },
  empty_note: {
    id: 'empty_note',
    name: 'Empty Note',
    description: 'This chest was empty.',
    type: 'quest',
    tags: ['lore'],
    category: 'lore',
    consumable: false,
    stackLimit: 1,
    icon: '📝'
  },
  focus_ring: {
    id: 'focus_ring',
    name: 'Focus Ring',
    description: 'Slightly improves the accuracy of all skills.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '🎯'
  },
  goblin_bow: {
    id: 'goblin_bow',
    name: 'Goblin Bow',
    description: 'A crude bow taken from a goblin archer.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '🏹'
  },
  goblin_sword: {
    id: 'goblin_sword',
    name: 'Goblin Sword',
    description: 'Crude blade favored by goblins.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '🗡️'
  },
  commander_badge: {
    id: 'commander_badge',
    name: 'Commander Badge',
    description: 'Proof of defeating the scout commander.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: false,
    stackLimit: 1,
    icon: '🎖️'
  },
  faded_blade: {
    id: 'faded_blade',
    name: 'Faded Blade',
    description:
      'A worn weapon once carried by Vaelin. Use in battle to strike harder.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 1,
    icon: '🗡️',
    useInCombat: true
  },
  scout_blade: {
    id: 'scout_blade',
    name: 'Scout Blade',
    description: 'A light blade once wielded by a goblin scout.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 1,
    icon: '🔪'
  },
  bone_shard: {
    id: 'bone_shard',
    name: 'Bone Shard',
    description: 'Fragment used in defense-crafting rituals.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🦴'
  },
  rotting_heart: {
    id: 'rotting_heart',
    name: 'Rotting Heart',
    description: 'Still oozing with foul ichor.',
    type: 'quest',
    tags: ['lore'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '❤️'
  },
  cracked_helmet: {
    id: 'cracked_helmet',
    name: 'Cracked Helmet',
    description: 'Offers minimal protection despite the damage.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '🪖'
  },
  mana_gem: {
    id: 'mana_gem',
    name: 'Mana Gem',
    description: 'Refreshes all skill cooldowns once.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 99,
    icon: '🔮',
    useInCombat: true
  },
  ward_leaf: {
    id: 'ward_leaf',
    name: 'Ward Leaf',
    description: 'Used later for crafting defense-enhancing items.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🍃'
  },
  old_scroll: {
    id: 'old_scroll',
    name: 'Old Scroll',
    description: 'Triggers hidden dialogue with a future ally.',
    type: 'quest',
    tags: ['lore'],
    category: 'lore',
    consumable: false,
    stackLimit: 1,
    icon: '📜'
  },
  arcane_spark: {
    id: 'arcane_spark',
    name: 'Arcane Spark',
    description: 'Unleashes a burst damaging all foes once per battle.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 3,
    icon: '✨',
    useInCombat: true
  },
  sentry_plating: {
    id: 'sentry_plating',
    name: 'Sentry Plating',
    description: 'Metal scrap useful for future armor crafting.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🛡️'
  },
  chaos_organ: {
    id: 'chaos_organ',
    name: 'Chaos Organ',
    description: 'Rare organ from rift creatures used in potent fusions.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🧬'
  },
  void_residue: {
    id: 'void_residue',
    name: 'Void Residue',
    description: 'Traded among scholars for high-level crafting.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🕳️'
  },
  crystal_shard: {
    id: 'crystal_shard',
    name: 'Crystal Shard',
    description: 'A faintly glowing fragment used for skill upgrades.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🔷'
  },
  defense_potion_II: {
    id: 'defense_potion_II',
    name: 'Defense Potion II',
    description: 'Increases defense by 2 for this fight.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 10,
    icon: '🧴',
    useInCombat: true
  },
  flesh_crystal: {
    id: 'flesh_crystal',
    name: 'Flesh Crystal',
    description: 'Used to enhance life-based skills (future).',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🧬'
  },
  crystal_dust: {
    id: 'crystal_dust',
    name: 'Crystal Dust',
    description: 'Required for crafting crystalline armor later.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '✨'
  },
  prism_fragment: {
    id: 'prism_fragment',
    name: 'Prism Fragment',
    description: 'A shimmering piece of condensed prism memory.',
    type: 'material',
    tags: ['items'],
    category: 'crafting',
    consumable: true,
    stackLimit: 99,
    icon: '🔶'
  },
  psy_fiber: {
    id: 'psy_fiber',
    name: 'Psy Fiber',
    description: 'Component in neural implants or debuff skills.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🧠'
  },
  rift_eye: {
    id: 'rift_eye',
    name: 'Rift Eye',
    description: 'May open a sealed psychic gate elsewhere.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: false,
    stackLimit: 1,
    icon: '👁️'
  },
  memory_gem: {
    id: 'memory_gem',
    name: 'Memory Gem',
    description: 'Can be socketed or traded for a skill token.',
    type: 'material',
    tags: ['lore'],
    category: 'lore',
    consumable: false,
    stackLimit: 99,
    icon: '🔮'
  },
  rift_fragment: {
    id: 'rift_fragment',
    name: 'Rift Fragment',
    description: 'A fragment pulsing with dimensional energy.',
    type: 'quest',
    tags: ['lore'],
    category: 'lore',
    consumable: false,
    stackLimit: 1,
    icon: '💠'
  },
  stamina_dust: {
    id: 'stamina_dust',
    name: 'Stamina Dust',
    description: 'Restores one skill cooldown instantly.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 10,
    icon: '💨',
    useInCombat: true
  },
  skill_token: {
    id: 'skill_token',
    name: 'Skill Token',
    description: 'Grants +1 max skill slot on the next map.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '🔶'
  },
  reflect_potion: {
    id: 'reflect_potion',
    name: 'Reflect Potion',
    description: 'Reflects the next damage back to the enemy.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🔄',
    useInCombat: true
  },
  blood_resin: {
    id: 'blood_resin',
    name: 'Blood Resin',
    description: 'Used in advanced leech-type recipes.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🩸'
  },
  echo_splinter: {
    id: 'echo_splinter',
    name: 'Echo Splinter',
    description: 'May unlock new dialogue in the next area.',
    type: 'quest',
    tags: ['lore'],
    category: 'lore',
    consumable: false,
    stackLimit: 1,
    icon: '✨'
  },
  crystal_seed: {
    id: 'crystal_seed',
    name: 'Crystal Seed',
    description: 'A key ingredient for item upgrade recipes.',
    type: 'material',
    tags: ['items'],
    category: 'crafting',
    consumable: true,
    stackLimit: 99,
    icon: '🌱'
  },
  mana_scroll: {
    id: 'mana_scroll',
    name: 'Mana Scroll',
    description: 'Completely restores skill cooldowns.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 3,
    icon: '📜',
    useInCombat: true
  },
  prism_key: {
    id: 'prism_key',
    name: 'Prism Key',
    description: 'Unlocks the door to the final mirror.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: false,
    stackLimit: 1,
    icon: '🗝️'
  },
  maze_key_1: {
    id: 'maze_key_1',
    name: 'Maze Key 1',
    description: 'Opens the western maze gate in the Gatepoint Room.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: false,
    stackLimit: 1,
    icon: '🗝️'
  },
  maze_key_2: {
    id: 'maze_key_2',
    name: 'Maze Key 2',
    description: 'Opens the northern gate in the Gatepoint Room.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: false,
    stackLimit: 1,
    icon: '🗝️'
  },
  clarity_shard: {
    id: 'clarity_shard',
    name: 'Clarity Shard',
    description: 'Use in combat to clear debuffs and gain "Focus".',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 3,
    icon: '🔷',
    useInCombat: true
  },
  gentle_flask: {
    id: 'gentle_flask',
    name: 'Gentle Flask',
    description: 'Restores 2 HP outside combat.',
    type: 'usable',
    tags: ['usable'],
    category: 'general',
    consumable: true,
    stackLimit: 5,
    icon: '🥤'
  },
  dreamleaf: {
    id: 'dreamleaf',
    name: 'Dreamleaf',
    description: 'Can be used later to mix with herbs for potions.',
    type: 'material',
    tags: ['items'],
    category: 'crafting',
    consumable: true,
    stackLimit: 99,
    icon: '🌿'
  },
  ember_residue: {
    id: 'ember_residue',
    name: 'Ember Residue',
    description: 'Warm fragments left behind by fiery foes.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🔥'
  },
  forgotten_ring: {
    id: 'forgotten_ring',
    name: 'Forgotten Ring',
    description: 'A simple ring that improves attack slightly.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '💍'
  },
  aegis_invocation_scroll: {
    id: 'aegis_invocation_scroll',
    name: 'Aegis Invocation Scroll',
    description: 'Using it teaches the Aegis Invocation skill.',
    type: 'quest',
    tags: ['lore'],
    category: 'lore',
    consumable: true,
    stackLimit: 1,
    icon: '📜'
  },
  ritual_oil: {
    id: 'ritual_oil',
    name: 'Ritual Oil',
    description: 'Use in combat to enhance mystical attacks.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 3,
    icon: '🛢️',
    useInCombat: true
  },
  polished_shard: {
    id: 'polished_shard',
    name: 'Polished Shard',
    description: 'Smooth fragment etched with temple runes.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '💎'
  },
  temple_resin: {
    id: 'temple_resin',
    name: 'Temple Resin',
    description: 'Fragrant sap once burned in rituals.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🕯'
  },
  ritual_oil: {
    id: 'ritual_oil',
    name: 'Ritual Oil',
    description: 'Oily blend used to anoint sacred altars.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🛢️'
  },
  mana_ember: {
    id: 'mana_ember',
    name: 'Mana Ember',
    description: 'Restores skill energy when used in combat.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🔥',
    useInCombat: true
  },
  ember_prayer_scroll: {
    id: 'ember_prayer_scroll',
    name: 'Ember Prayer Scroll',
    description: 'Using it teaches the Ember Prayer skill.',
    type: 'quest',
    tags: ['lore'],
    category: 'lore',
    consumable: true,
    stackLimit: 1,
    icon: '📜'
  },
  volcanic_slag: {
    id: 'volcanic_slag',
    name: 'Volcanic Slag',
    description: 'Powers up fiery abilities when used in combat.',
    type: 'combat',
    tags: ['combat'],
    category: 'combat',
    consumable: true,
    stackLimit: 5,
    icon: '🌋',
    useInCombat: true
  },
  cracked_chime: {
    id: 'cracked_chime',
    name: 'Cracked Chime',
    description: 'A damaged chime traded among collectors.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🔔'
  },
  veil_powder: {
    id: 'veil_powder',
    name: 'Veil Powder',
    description: 'Rare dust used in stealth brews.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🌫️'
  },
  temple_sword: {
    id: 'temple_sword',
    name: 'Temple Sword',
    description: 'A blade resonating with ancient power.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '🗡️'
  },
  temple_shell: {
    id: 'temple_shell',
    name: 'Temple Shell',
    description: 'Hardened armor bearing sacred sigils.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '🛡️'
  },
  temple_ring: {
    id: 'temple_ring',
    name: 'Temple Ring',
    description: 'An ornate band linked to temple rites.',
    type: 'gear',
    tags: ['equipable'],
    category: 'equipable',
    consumable: false,
    stackLimit: 1,
    icon: '💍'
  },
  vicar_sigil: {
    id: 'vicar_sigil',
    name: 'Vicar Sigil',
    description:
      'Proof of dominion over the Stonebound Vicar. Unlocks sacred doors.',
    type: 'key',
    tags: ['lore'],
    category: 'key',
    consumable: false,
    stackLimit: 1,
    icon: '🗝️'
  },
  echo_crystal: {
    id: 'echo_crystal',
    name: 'Echo Crystal',
    description: 'Resonates with lost voices, used for upgrades.',
    type: 'material',
    tags: ['items'],
    category: 'general',
    consumable: true,
    stackLimit: 99,
    icon: '🔮'
  }
};

export function getItemDataLocal(id) {
  return itemData[id];
}
