import fs from 'fs';
import path from 'path';

const npcDir = path.join(process.cwd(), 'scripts', 'npc');
const indexFile = path.join(npcDir, 'index.js');

const files = fs
  .readdirSync(npcDir)
  .filter((f) => f.endsWith('.js') && f !== 'index.js')
  .sort();

function toVarName(file) {
  const base = file.replace(/\.js$/, '');
  let name = base.replace(/[^a-zA-Z0-9_$]/g, '_');
  if (/^[0-9]/.test(name)) {
    name = '_' + name;
  }
  return { base, name };
}

const importLines = [];
const exportLines = [];
for (const file of files) {
  const { base, name } = toVarName(file);
  importLines.push(`import * as ${name} from './${file}';`);
  if (base === name) {
    exportLines.push(`  ${name}`);
  } else {
    exportLines.push(`  '${base}': ${name}`);
  }
}

const content = `// AUTO-GENERATED BY tools/build_npc_index.js\n// DO NOT EDIT MANUALLY\n\n${importLines.join('\n')}\n\nexport const npcModules = {\n${exportLines.join(',\n')}\n};\n`;

fs.writeFileSync(indexFile, content);
